# Generated by Django 3.2.4 on 2021-07-12 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_events_id_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='call_recording',
            field=models.CharField(default='puk', max_length=500),
        ),
        migrations.AlterField(
            model_name='events',
            name='id_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
    ]
