# Generated by Django 3.2.4 on 2021-07-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210712_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='description',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='first_name',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='clients',
            name='last_name',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='call_recording',
            field=models.CharField(default='empty', max_length=500),
        ),
    ]
