# Generated by Django 3.2.4 on 2021-07-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210712_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='sc',
            field=models.ManyToManyField(to='api.ClientPhones'),
        ),
    ]
