# Generated by Django 3.2.4 on 2021-07-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_events_sc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='sc',
        ),
    ]
