# Generated by Django 3.2.4 on 2021-07-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_events_sc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientphones',
            name='id_clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='api.clients'),
        ),
        migrations.AlterField(
            model_name='employeesphones',
            name='id_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id_employees_phones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_name', to='api.employeesphones'),
        ),
    ]
